import Head from 'next/head'
import MeetupList from '@/components/meetups/MeetupList'
import { useEffect, useState } from 'react'

// const inter = Inter({ subsets: ['latin'] })

const DumYY_me = [
  {

    id: "1",
    image: 'https://picsum.photos/200/300',
    title:  'Title',
    address: 'Address',
    discription: 'discription'
  },
  {

    id: "2",
    image: 'https://picsum.photos/200/300',
    title:  'Title 2',
    address: 'Address 2',
    discription: 'discription'
  }
]

export default function Home() {
  const [loadeMeetups, setLoadeMeetups ]= useState()

  useEffect(() => {
    // send a http req and fetch data
    setLoadeMeetups(DumYY_me)
  },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main > 
           <MeetupList meetups={loadeMeetups}/>
      </main>
    </>
  )
}
